### ISSUE TITLE
User should be able to add dishes. -By Samip

### ISSUE THREAD

**Issue by Samip1211** [jlug331221/TTU-SPM-Spring2017#10]

**Comment by jlug331221** [comment]
As the scrum master, I would like to have an update of this user story sometime early this week. The reason for this is because the story/issue was opened 21 days ago. I just need to know if I can help in any way.

**Comment by jlug331221** [comment]
This user story seems to be the same as #14. Am I correct in assuming so? If so, then we can remove this issue and use the one for #14 instead.
